name: 'Setup QMK firmware'
description: 'Setup QMK firmware for building'

inputs:
  version:
    default: '0.22.14'
    required: false
    description: 'QMK firmware version to use'
  path:
    default: '__qmk__'
    required: false
    description: 'Path to store QMK firmware'

runs:
  using: 'composite'
  steps:

  - name: Checkout qmk_firmware
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    with:
      path: ${{ inputs.path }}
      repository: qmk/qmk_firmware
      submodules: recursive
      ref: ${{ inputs.version }}

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes